name: iOS Build

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Decode and configure certificates
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > private_key.p8
        echo "${{ secrets.CERTIFICATES_P12 }}" | base64 --decode > certificates.p12
        security create-keychain -p actions keychain-db
        security import private_key.p8 -k ~/Library/Keychains/keychain-db -P "" -T /usr/bin/codesign
        security import certificates.p12 -k ~/Library/Keychains/keychain-db -P ${{ secrets.CERTIFICATES_P12_PASSWORD }} -T /usr/bin/codesign
        security list-keychains -s ~/Library/Keychains/keychain-db
        security default-keychain -s ~/Library/Keychains/keychain-db
        security unlock-keychain -p actions ~/Library/Keychains/keychain-db
        security set-key-partition-list -S apple-tool:,apple: -s -k actions ~/Library/Keychains/keychain-db
      env:
        CERTIFICATES_P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - name: Install CocoaPods
      run: bundle exec pod install
      working-directory: ./SSGaming

    - name: Build IPA
      run: |
        xcodebuild clean archive \
          -project SSGaming.xcodeproj \
          -scheme SSGaming \
          -archivePath $GITHUB_WORKSPACE/build/SSGaming.xcarchive \
          -configuration Release \
          -allowProvisioningUpdates \
          CODE_SIGN_IDENTITY="iPhone Distribution" \
          PROVISIONING_PROFILE_SPECIFIER="com.webapp.testBuild"

        xcodebuild -exportArchive \
          -archivePath $GITHUB_WORKSPACE/build/SSGaming.xcarchive \
          -exportPath $GITHUB_WORKSPACE/build/ \
          -exportOptionsPlist ./SSGaming/exportOptions.plist
      working-directory: ./SSGaming

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ipa
        path: $GITHUB_WORKSPACE/build/*.ipa
